baseURL = 'https://ChenLiang-lab.github.io/'
theme = 'stack'
defaultContentLanguage = 'zh-cn'
title = 'ChenLiang-lab ?????'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '??'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'posts'
    name = '??'
    url = '/post/'
    weight = 3
  [[menu.main]]
    identifier = 'tags'
    name = '??'
    url = '/tags/'
    weight = 4

[pagination]
    pagerSize = 5

[permalinks]
    post = '/:slug/'

[params]
  mainSections = ['post']

  [params.footer]
    since = 2026

  [params.sidebar]
    compact = false

  [params.article]
    toc = true
    readingTime = true
    [params.article.list]
      showTags = true

  [params.widgets]
    homepage = [
      { type = 'recent-posts', params = { limit = 5 } }
    ]
    page = [
      { type = 'toc' },
      { type = 'categories', params = { limit = 10 } },
      { type = 'archives', params = { limit = 10 } },
      { type = 'tag-cloud' }
    ]

  [params.colorScheme]
    toggle = true
    default = 'auto'

  [params.imageProcessing]
    [params.imageProcessing.content]
      widths = [800, 1600, 2400]
      enabled = true
    [params.imageProcessing.thumbnail]
      enabled = true

[outputs]
  home = ['HTML', 'RSS', 'JSON']
  section = ['HTML', 'RSS']
